spring.application.name=music-backend
#spring.datasource.url=jdbc:mysql://localhost:3306/music_player
#
#spring.datasource.username=root
#spring.datasource.password=9912238506@Raj
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.password=yXgmMFTKCKInvaBVJNLvuZobxRQMUWwA

spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:29436/railway
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
server.address=0.0.0.0
